---
title: "Lab 2"
author: "Group Member Names - here"
output: word_document
---

Turn in one copy for each group, both as a word or PDF document and the R Markdown source file.

## Lab Overview

This lab will explore a dataset containing Paycheck Protection Program (PPP) loans issued in the state of Montana with total loan amounts greater that $150,000. The data was acquired via [kaggle.com](https://www.kaggle.com/susuwatari/ppp-loan-data-paycheck-protection-program). The source data can also be found at on the Department of the Treasury [Website](https://home.treasury.gov/policy-issues/cares-act/assistance-for-small-businesses/sba-paycheck-protection-program-loan-level-data).

The entire lab will be worth 20 points.

## Questions
Answer the following questions in this R Markdown document. Please include code where necessary.


### 1. Download Data (2 points)
Download the dataset, which has been filtered to only include businesses in Montana. The data is available at [https://raw.githubusercontent.com/stat408/Lab2/master/MT_PPP.csv](https://raw.githubusercontent.com/stat408/Lab2/master/MT_PPP.csv).

### 2. Data Description (2 points)

Summarize the dataset. In particular focus on:

- How many businesses are in the dataset?
- What attributes are collected for each business?


### 3. Total Jobs Retained (2 points)
According to the data, how many total jobs were "retained?"


### 4. Maximum Jobs Retained (2 points)

What are the maximum number of jobs retained by a single business?

### 5. Bozeman Jobs Retained (2 points)

How many jobs were retained for businesses based in Bozeman?

### 6. Count by Business Type (2 points)

How many businesses of each business type received loans?

### 7. Count by City (2 points)

Which 5 cities have the most loans?

### 8. Maximum Jobs Retained (2 points)

Which business(es) claimed the maximum number of jobs retained?

### 9. Data Visualization (4 points)

Create a data visualization using `ggplot2` that summarizes some aspect of this dataset.
